// <auto-generated />
using System;
using DotNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCore.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20190614111154_MovieSampleApp")]
    partial class MovieSampleApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCore.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageUrl");

                    b.Property<string>("Genre");

                    b.Property<bool>("IsWatched");

                    b.Property<decimal>("Price");

                    b.Property<int>("QualityId");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("DotNetCore.Models.MovieQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Quality");

                    b.HasKey("Id");

                    b.ToTable("MovieQualities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quality = "HD"
                        },
                        new
                        {
                            Id = 2,
                            Quality = "720p"
                        },
                        new
                        {
                            Id = 3,
                            Quality = "1080p"
                        },
                        new
                        {
                            Id = 4,
                            Quality = "4k"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
